.gitignore

Creación del branch productos, además de preparación de ambiente de desarrollo, un archivo en el .gitignore "desktop.ini" que no requieren los demás.

Preparando ambiente para desarrollo

---

controllers/ProductoController.js
database/ProductoDB.js
domain/Producto.js
index.js
preload.js
public/js/dashboard-js/dashboard.js
services/ProductoService.js

fec: 11-03-2025 | Avance en el método de listar productos, se crearon los archivos ProductoDB, ProductoService, ProductoController, y la creación de los métodos en preload.js, index.js, TODO: Queda pendiente la implementación en el archivo dashboard.js para la visualización en el frontend.

| Avance en el método de listar productos |

---

controllers/ProductoController.js
database/ColaboradorDB.js
database/ConectarDB.js
database/ProductoDB.js
index.js
package-lock.json
package.json
public/js/dashboard-js/dashboard.js
services/ProductoService.js

Corrección de listado de colaboradores y corrección de listado de puesto de trabajo. Archivos modificados ProductoDB.js, index.js, dashboard.js

Unión de Corrección-de-errores-de-listado... con rama productos

---

database/CategoriaProductoDB.js

El método para actualizar la categoría en el acceso a datos ya está listo, solo basta con entra al proyecto, ejecutarlo y tratar de actualizar una categoría de producto, el resultado debe de ser éxito.

Método de actualizar categoría en el acceso a datos.

---

controllers/FacturaController.js
controllers/FacturaProductoController.js
database/ConectarDB.js
database/FacturaBD.js
database/FacturaProductoDB.js
domain/FacturaProducto.js
index.js
preload.js
public/CSS/dashboard-css/dashboard.css
public/js/dashboard-js/dashboard.js
services/FacturaProductoService.js
services/FacturaService.js
views/dashboard/dashboard.html
views/factura-view/detalles-factura.html
views/factura-view/factura-admin.html

Tarea de poder leer la información de todas las facturas registradas complete, ya existe el listado de facturas con algunos de sus detalles en una tabla, todo debidamente paginado, pero no solo eso, sino que también ya está el que se pueda visualizar los detalles completos de la factura, con todo y la lista de productos que pertenecen a la factura.
Para revisar lo hecho en esta PR, solo basta con ejecutar la aplicación y acceder a administrar facturas en el menu lateral izquierdo, de inmediato verán una lista de facturas paginadas, y al clicar en el botón de ver detalles podrán dar click para acceder a donde se ve toda la info de la factura especifica con su lista de productos, en esta vista incluso pueden clicar el botón de imprimir que ya es funcional.

Poder leer la información de todas las facturas registradas 

---

controllers/ComprobantePagoController.js
database/ComprobantePagoDB.js
database/FacturaProductoDB.js
database/ProveedorDB.js
index.js
preload.js
public/js/dashboard-js/dashboard.js
services/ComprobanteDePagoService.js
views/factura-view/factura-admin.html

- Filtrado por proveedor completo.
- Filtrado por Comprobante completo.
- Filtrado por estado de factura completo.
- Barra de navegación funcional.
- Filtrado por rangos de fecha completo.
1. En github moverse a la rama de esta PR
2. Ejecutar la aplicación
3. Dar click a la opción de Administrar Facturas en el menú lateral izquierdo.
4. Una vez se cargue la lista de facturas, utilizar cualquiera de los select de filtrado para comprobar su funcioanlidad.

Filtrado de factura listo

---

database/CategoriaProductoDB.js
database/ConectarDB.js
database/ProductoDB.js
index.js
preload.js
public/js/dashboard-js/dashboard.js
views/configuration-panel/configuration-panel.html
views/configuration-panel/productos-admin.html

Se puede hacer uso de la funcionalidad para listar todos los productos (pasando por parametro pageSize = null y currentPage = null) o paginados con el valor pageSize deseado.

Listar productos funcional

---

database/ProductoDB.js
index.js
public/js/dashboard-js/dashboard.js
services/ProductoService.js
views/configuration-panel/productos-admin.html

Leer todos los productos que se encuentran registrados y filtrarlos por cualquier palabra relacionada, ya sea por nombre o categoría.

ING1234-16 - Leer productos y filtrarlos.

---

database/ProductoDB.js

Se añadió una verificacion en ProductoBD que evite la eliminación de los parametros de filtro en caso de que pageSize y currentPage no esten definidos.

Correccion de error de sintaxis sql.

---

controllers/ProductoController.js
database/ProductoDB.js
index.js
preload.js
public/CSS/dashboard-css/dashboard.css
public/js/dashboard-js/dashboard.js
services/ProductoService.js
views/configuration-panel/productos-admin.html

Se generó el formulario para la creacion de un producto que cuente con los campos de nombre, descripcion, cantidad, unidad de medicion y categoria. Se registra en la BD con éxito. Se agregaron validaciones para que se pueda guardar un producto sin cantidad ni descrpcion.

Ing1234 15 crear un producto con nombre descripcion y categoria.

---

database/ProductoDB.js
public/CSS/dashboard-css/dashboard.css
public/js/dashboard-js/dashboard.js
services/ProductoService.js

Aquí van los estilos para las filas de los productos que tengan una cantidad igual o menor a 10. Además incluí la correción de la sintaxis SQL que había desaparecido. Hay código comentado que voy a implementar mañana, se me olvidó cuál era la función que estaba destinada en un principio, luego me acordé y por eso lo dejé.

Ing1234 73 generar una lista de los productos que tengan una cantidad menor a 10 en el inventario

---

controllers/FacturaProductoController.js
database/FacturaBD.js
database/FacturaProductoDB.js
database/UsuarioDB.js
index.js
preload.js
public/js/dashboard-js/facturas.js
services/FacturaProductoService.js
views/factura-view/crear-factura.html
views/factura-view/factura-admin.html

Se ha completado el crear una factura, de modo que al clicar en el botón de crear factura se muestra un formulario de creación solicitando los datos tanto de la factura en si, como de los productos que irán asociados a la factura, y los datos relevantes para la tabla relacional facturaproducto.
##
Es probable que al clicar en crear la primera vez no carguen los select de proveedor y comporbante de pago, solo se clica en retroceder y se vuelve a clicar en crear y debería de funcionar.
##
Es necesario tener datos en las siguientes tablas:
- sigm_producto
- sigm_factura
- sigm_categoria_producto
- sigm_proveedor
- sigm_comprobante_pago
- sigt_factura_producto
- sigm_colaborador
- sigm_usuario
- sigm_departamento
- sigm_puesto_trabajo

Ing1234 48 poder crear una factura

---

controllers/ProductoController.js
database/ConectarDB.js
database/ProductoDB.js
index.js
preload.js
public/js/dashboard-js/dashboard.js
services/ProductoService.js

Se agregó la funcionalidad de deshabilitar y rehabilitar un producto.

ING1234-18. Deshabilitar un producto con alerta de confirmación

---

controllers/ProductoController.js
database/ConectarDB.js
database/ProductoDB.js
index.js
preload.js
public/CSS/dashboard-css/dashboard.css
public/js/dashboard-js/dashboard.js
services/ProductoService.js
views/configuration-panel/productos-admin.html

Ya se puede actualizar un producto. Se añadieron algunos estilos en caso de que la categoría se encuentre deshabilitada. las clases para que luzcan bien son: 
- .categoria-inactiva
- option:disabled
- select:disabled option:checked

Ing1234 17 Edición de datos de un producto.

---

backup/dbsigesa_estandarizada 28-03-2025 21.16.sql
database/EntidadFinancieraDB.js
domain/EntidadFinanciera.js
index.js
preload.js
public/js/dashboard-js/dashboard.js
services/EntidadFinancieraService.js
views/configuration-panel/entidades-financieras-admin.html

Caso de prueba:
- Generar una lista desplegable de todas las entidades financieras.
- Ingresar a un módulo que requiera una lista de las entidades financieras.
- Verificar que se muestran los registros al seleccionar el select respectivo.
- Realizar una búsqueda desde el input con cualquier palabra.
- Probar los filtros de paginación y estado.
- Navegar entre las páginas.
Resultado esperado:
Se muestran todos los registros, estos se filtran según los filtros que se apliquen, sean de cantidad por página o por búsqueda.

Ing1234 62 listar entidades financieras

---

database/EntidadFinancieraDB.js
index.js
preload.js
public/js/dashboard-js/dashboard.js

Casos de prueba:
- Ingresar al módulo de “Administrar entidades financieras”.
- Seleccionar el botón de crear una entidad.
- Se muestra el formulario de creación con los campos respectivos.
- Se validan los datos obligatorios al intentar enviar el formulario sin los datos.
- Envío del formulario y mensaje de confirmación

ING1234-51 crear formulario para el registro de entidades financieras

---

database/EntidadFinancieraDB.js
index.js
preload.js
public/js/dashboard-js/dashboard.js
views/configuration-panel/entidades-financieras-admin.html

**Casos de prueba:**
1. Ingresar al módulo de “Administrar entidades financieras”.
2. Seleccionar el botón de edición.
3. Visualizar los datos asociados a la entidad financiera.

ING1234-55 | Editar entidades financieras

---

database/ConectarDB.js
database/UsuarioDB.js
public/js/dashboard-js/dashboard.js

*Se ha modificado la condicional en el método de edición de usuarios que impide que al editar el usuario el nombre de usuario este repetido con el de otro, de modo que ahora no solo revisa que el nombre de usuario no esté ya tomado, sino que además revisa que no sea por el mismo usuario que se está editando, de modo que si se edita el usuario y el nombre de usuario se deja intacto, cuando se compare en la base de datos y se revise que el nombre de usuario ya existe, se valida si existe para otro usuario que no sea el que está siendo editado, de modo que si el nombre de usuario existe pero para el mismo usuario, se deja hacer la edición*
##
1. Permitir edición si el nombre de usuario ya está tomado por el mismo usuario:
- Dado que un usuario intenta actualizar su nombre de usuario a uno …

10/04/2025 Solución de edición de usuarios lista

---

controllers/ProductoController.js
database/ConectarDB.js
database/ProductoDB.js
database/PuestoDB.js
index.js
package-lock.json
package.json
preload.js
public/CSS/dashboard-css/dashboard.css
public/js/dashboard-js/dashboard.js
public/js/dashboard-js/productos.js
services/ProductoService.js
views/configuration-panel/productos-admin.html
views/dashboard/dashboard.html

*Se han agregado los botones de generar reporte PDF y Excel del inventario en el apartado de gestionar los productos, de modo que al clicarlos se generan en el escritorio para poder visualizarlos*
##
*Iniciar el programa y dirigirse a la configuración, ahí seleccionar la opción de Administrar Productos, una vez se cargue la ventana se verán los 2 botones, uno para PDF y otro para excel, clicar cualquiera de los 2, se verá un toast indicando el exito y el lugar en el cual se generaron los reportes, este será el escritorio.*
##
1. El sistema debe establecer una sección donde se pueda apreciar una opción que facilite la gestión de reportes de los productos existentes en el inventario.
2. 
3. En esta sección se presentan filtros que se aplican al resultado final, dichos filtros son reporte …

Ing1234 23 generar archivos en formato pdf o excel para reportes de inventario

---

domain/ModuleSelector.js
public/js/dashboard-js/dashboard.js
views/configuration-panel/configuration-panel.html
views/configuration-panel/productos-admin.html

Corrección de bugs con respecto al listado y la interacción del select

ING1234-96 Listado unidades desde select producto

---

controllers/UnidadMedicionController.js
database/UnidadMedicionDB.js
domain/ModuleSelector.js
index.js
preload.js
public/js/dashboard-js/dashboard.js
services/UnidadMedicionService.js
views/dashboard/dashboard.html

**Criterios de aceptación:**
1. Al ingresar al apartado de administración de productos y seleccionar el select de unidades de medición se muestra un ícono “X“ para comenzar la acción de deshabilitar alguna unidad.
2. Tras hacer clic sobre el ícono “X“ se muestran dos opciones “Eliminar” y “Cancelar”.
3. La opción de cancelar deshabilita visualmente las dos opciones anteriores.
4. La opción de eliminar valida que la unidad no se encuentre asociada a un producto para luego deshabilitarla.
**Plan de pruebas:**
1. Ingreso al apartado de administración de productos.
2. Clic sobre el ícono de creación de un producto.
3. Hacer clic sobre el select de unidades de medición.
4. Hacer clic sobre el ícono de “X“.
5. Se muestran las dos opciones de Eliminar y cancelar.
6. Eliminar valida que la unidad …

ING1234-98 | Deshabilitar unidades desde select Completado.

---

public/js/dashboard-js/dashboard.js

Este select, al seleccionar la categoría del producto por el cual se quiere filtrar la lista, este hace su funcionamiento correcto mostrando una lista de productos filtrados correctamente, sin embargo, se resetea instantáneamente el select volviendo a colocar como seleccionada la opción que viene por defecto de “seleccionar categoría”, esto no afecta el filtrado, pero si cosas como el generar reportes con ese filtro.
Plan de pruebas:
1. Ingresar al listado de productos, ya sea desde administrar inventario o productos dentro del panel de configuración.
2. Seleccionar el filtro por categoría en cualquier opción.
3. Exportar el listado en PDF o EXCEL.
4. Verificar el contenido del exportable.

ING1234-100 | Corregir filtro select listado productos

---

controllers/PuestoTrabajoController.js
index.js
public/js/dashboard-js/dashboard.js
services/PuestoTrabajoService.js
views/configuration-panel/puestro-trabajo.html

Debe existir un botón o enlace visible para agregar un nuevo puesto.
El formulario debe abrirse vacío para nuevos registros.
El formulario debe permitir ingresar todos los datos necesarios de un puesto (nombre, departamento, estado, etc.).
Al guardar, el nuevo puesto debe aparecer en la lista.
Si faltan campos obligatorios, el sistema debe mostrar mensajes de validación.
Si el usuario cancela el formulario, no se debe registrar ningún nuevo puesto.
El sistema debe evitar registros duplicados si se define esa restricción.
Abrir formulario de nuevo puesto
Desde la vista de la lista
Hacer clic en “Agregar nuevo puesto”
Comprobar que se abre el formulario con todos los campos vacíos
Resultado esperado: Se muestra el formulario vacío para registrar un nuevo puesto.
Registrar nuevo puesto …

Ing1234 80 generar un formulario donde se pueda ingresar la información de un puesto de trabajo para registrarlo 

---

database/ConectarDB.js
preload.js
public/js/dashboard-js/dashboard.js
views/dashboard/dashboard.html

Se ocultan elementos del DOM según el rol que posea el usuario, en este caso si es asistente se ocultarán dos vistas administrativas, usuarios y empleados.
Para probar la funcionalidad se debe crear un usuario desde la vista administrativa de usuarios con el rol asistente. Como resultado se deben ocultar dos opciones administrativas: Desde el Dashborad se oculta administrar usuarios y desde el configuration-panel se oculta administrar empleados.

ING1234-104-Filtro-opciones-por-rol
